# Generated by Django 3.0.2 on 2020-01-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maserati',
            name='year',
            field=models.IntegerField(),
        ),
    ]
